<a href="https://colab.research.google.com/github/galievaz/ISAC/blob/master/Task2/2_Custom_review_classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math
import random

In [ ]:
#loading the dataset
dataset = pd.read_csv("6-reviews_amazon_stars.csv")


In [ ]:
print(dataset.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49985 entries, 0 to 49984
Data columns (total 2 columns):
star    49985 non-null int64
text    49985 non-null object
dtypes: int64(1), object(1)
memory usage: 781.1+ KB
None


In [ ]:
print(dataset.head())

   star                                               text
0     4  Sometimes sticks a little on my Samsung Nexus,...
1     3  Sometimes you have to push down on the keys fo...
2     4  The stylus is excellent. It works as well as d...
3     4  Bought this product about 10 months ago and st...
4     5  This is an expensive stylus, so I'm hesitant t...


In [ ]:
print(dataset.describe())

               star
count  49985.000000
mean       3.748765
std        1.488922
min        1.000000
25%        3.000000
50%        4.000000
75%        5.000000
max        5.000000


""" cleaning the dataset is like preparing our dataset to apply our machine learning model. The step include:
1. Get rid of the punctuations as this create many confusions of the words and difficult to understand.
2. steaming the dataset like sorting some words like loved, liked and converting them to love and like respectively.
3. converting all the uppercase letter to lower case letter.
4. get reid of the nuumbers, unless they are not relevent.
5. we will construct columns for each associated word and will count if it appears in the review or not. this will create more
zeros in our columns.
6. we will use sparse matrix as most of the part we will be having 0's as most are new words"""



In [ ]:
#cleaning the texts
#importing re as its is most used library to clean text.
import re
review = re.sub("[^a-zA-Z]", " ",  dataset["text"][0])




In [ ]:
print(review)

Sometimes sticks a little on my Samsung Nexus  but overall works very well  Also really like the built in pen feature 


In [ ]:
# the next process will be to convert all the letter to a lower case letter
review = review.lower()
print(review)

sometimes sticks a little on my samsung nexus  but overall works very well  also really like the built in pen feature 


In [ ]:
# now in the next process we will get rid of word which are of no use to us to judge the review like article, prepositions, etc.
#we need a library which contain most functions of NLP calles nltk
import nltk
nltk.download("stopwords")


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\128524\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
""" now we will run a for loop for all the review for the same process we done above for 1st review"""
review =review.split()
print(review)


['sometimes', 'sticks', 'a', 'little', 'on', 'my', 'samsung', 'nexus', 'but', 'overall', 'works', 'very', 'well', 'also', 'really', 'like', 'the', 'built', 'in', 'pen', 'feature']


In [ ]:
from nltk.corpus import stopwords
review = [word for word in review if not word in set(stopwords.words("english"))]
#the set function is used to speedup the algo as it guide fot the set of words in the list
print(review)

['sometimes', 'sticks', 'little', 'samsung', 'nexus', 'overall', 'works', 'well', 'also', 'really', 'like', 'built', 'pen', 'feature']


In [ ]:
#now appling stemming. we need to import porterstemmer
from nltk.stem.porter import PorterStemmer
#we will redesign our algorithem as the above process was to make understanding and now we can have a fun algorithem here.
ps = PorterStemmer()
#review = [ps.stem(word) for word in review if not word in set(stopwords.words("english"))]
print(review)

['sometimes', 'sticks', 'little', 'samsung', 'nexus', 'overall', 'works', 'well', 'also', 'really', 'like', 'built', 'pen', 'feature']


In [ ]:
#we will make a list containg all the words and so we use join command with space as to seperate the words for join in single word.
review = " ".join(review)
print(review)

sometimes sticks little samsung nexus overall works well also really like built pen feature


In [ ]:
#the same process we will perform for all 1000 review.
#we will make a list for all 1000 reviews names corpus
corpus = []
for i in range(len(dataset['star'])):
    review_1 = re.sub(r'[^a-zA-Z]', ' ', dataset['text'][i])
    review_1 = review_1.lower()
    review_1 = review_1.split()
    ps = PorterStemmer()
    #review_1 = [ps.stem(word) for word in review_1 if not word in set(stopwords.words('english'))]
    review_1 = ' '.join(review_1)
    corpus.append(review_1)
    

In [ ]:
corpus[:10]

['sometimes sticks a little on my samsung nexus but overall works very well also really like the built in pen feature',
 'sometimes you have to push down on the keys for it to work very cheap next time i will get a tip made from rubber',
 'the stylus is excellent it works as well as described in other reviews my only peeve with it is the pen doesn t fully retract into the stylus so while using it you occasionally write on your hand i would probably like it better if it didn t have a pen so far i have had no need for the pen i was just playing with it as i was writing this review and found that if i take it apart i can loosen the pen insert now it can fully retract however the insert isn t fully tight in the handle not a big deal since i don t use the pen i have an ipad with an incase leather cover the stylus fits nicely into the space where the cover folds and is secure when closed i was initially worried i would misplace the stylus at some point but storing it in the case works very w

In [ ]:
#creating a bag of word model, appluing the machine learning model and tranforming and predicting.
""" we will make a table containing all the review in one column. And then we choose a specific word and count the 
number of times the specific word appeared in the review """
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
#we can do use stemming , sorting and many other things in countvectorizer but can be more efficient doing it manually.
X = cv.fit_transform(corpus).toarray()


In [ ]:
print(X[:10])

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
print(X.shape)

(49985, 30467)


In [ ]:
#here we can see that the 30467 words are taken from the reviews and so we add a new parameter in countVectorizer a max_feature.
cv = CountVectorizer(max_features = 3600)
X = cv.fit_transform(corpus).toarray()
y = dataset.iloc[:, 1].values


In [ ]:
print(X.shape)

(49985, 3600)


In [ ]:
print(y.shape)

(49985,)


In [ ]:
""" we will train our model to predict of the review. The most common model used in Natual Language Processing are
naive bayes decision tree and random forest. We will use here naive bayes first""" 
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 42)

# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [ ]:
print(cm)

In [ ]:
from sklearn.metrics import classification_report
target =["negative add", "positive add"]
print(classification_report(y_test, y_pred, target_names=target))

              precision    recall  f1-score   support

negative add       0.52      0.31      0.39       108
positive add       0.45      0.65      0.53        92

    accuracy                           0.47       200
   macro avg       0.48      0.48      0.46       200
weighted avg       0.48      0.47      0.46       200



In [ ]:
a = (48+86)/200

In [ ]:
print("accuracy {}\n".format(a))

accuracy 0.67



In [ ]:
#Now we will train random forest to the dataset
from sklearn.ensemble import RandomForestClassifier
SEED = 1
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=SEED)
rf = RandomForestClassifier(n_estimators=400, min_samples_leaf=0.12,max_depth = 5,  random_state=SEED)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)
from sklearn.metrics import confusion_matrix
cm_rf = confusion_matrix(y_test, y_pred_rf)
print(cm_rf)


[[  0 108]
 [  0  92]]


In [ ]:
from sklearn.metrics import classification_report
target =["negative add", "positive add"]
print(classification_report(y_test, y_pred_rf, target_names=target))

              precision    recall  f1-score   support

negative add       0.00      0.00      0.00       108
positive add       0.46      1.00      0.63        92

    accuracy                           0.46       200
   macro avg       0.23      0.50      0.32       200
weighted avg       0.21      0.46      0.29       200



C:\Users\128524\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
